### ISSUE TITLE
TOR auto-publish-enabled property not honored

### ISSUE THREAD

**Issue by SpiReCZ** [theborakompanioni/bitcoin-spring-boot-starter#33] opened 2022-10-03 00:51 UTC
**Expected behavior**

Setting `org.tbk.tor.auto-publish-enabled=false` should disable auto publishing.

**Actual behavior**

Setting `org.tbk.tor.auto-publish-enabled=false` has no effect.
Application fails to configure.

**Steps to reproduce the problem**
  1. Set property `org.tbk.tor.auto-publish-enabled=false`
  2. Run Application
  3. Fail

**Specifications**
  - Version: 0.3.0
  - Platform: MacOS
  - Module: spring-tor-autoconfigure

`implementation("io.github.theborakompanioni:spring-tor-starter:0.3.0")`

Kotlin 1.6.21
Spring Boot 2.7.4
Gradle 7.5

**Additional context**

Log:
```
Caused by: java.lang.IllegalStateException: Cannot publish hidden service for application. Please specify 'server.port' or disable auto publishing with 'org.tbk.tor.auto-publish-enabled=false'
	at org.tbk.tor.spring.config.TorHiddenServiceAutoConfiguration.applicationHiddenServiceDefinition(TorHiddenServiceAutoConfiguration.java:42) ~[spring-tor-autoconfigure-0.3.0.jar:0.3.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	... 84 common frames omitted
```

Debug autoconfiguration output:
```
   TorHiddenServiceAutoConfiguration#applicationHiddenServiceDefinition matched:
      - @ConditionalOnBean (types: org.springframework.boot.autoconfigure.web.ServerProperties; SearchStrategy: all) found bean 'server-org.springframework.boot.autoconfigure.web.ServerProperties'; @ConditionalOnMissingBean (names: applicationHiddenServiceDefinition; SearchStrategy: all) did not find any beans (OnBeanCondition)
```
It looks like `@Conditional(OnAutoPublishEnabledAndServerPortSpecified.class)` is not evaluated at all.

**Comment by theborakompanioni** [comment] 2022-10-03 08:39
> It looks like `@Conditional(OnAutoPublishEnabledAndServerPortSpecified.class)` is not evaluated at all.

Thank you for the report and the detailed information! :orange_heart: 
The test did not really cover the intended behaviour.. 
Problem has been reproduced and fixed in #34.
Would you be able to test it?

**Comment by SpiReCZ** [comment] 2022-10-03 14:15
Thanks for a quick fix. I tried it locally and now it works as expected.
Can you produce a release with these changes?

Mitigation:

Kotlin:
```kotlin
@SpringBootApplication(
    exclude = [TorHiddenServiceAutoConfiguration::class]
)
```

Java:
```java
@SpringBootApplication(
    exclude = {TorHiddenServiceAutoConfiguration.class}
)
```

**Closed** 2022-10-03 15:22 UTC
Labels: bug

**Comment by theborakompanioni** [comment] 2022-10-03 17:35
> Can you produce a release with these changes?

[v0.4.0](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/releases/tag/0.4.0) released.
